name       : libguestfs
version    : 1.40.2
release    : 1
source     :
    - http://download.libguestfs.org/1.40-stable/libguestfs-1.40.2.tar.gz : ad6562c48c38e922a314cb45a90996843d81045595c4917f66b02a6c2dfe8058
license    : LGPLv2+
component  : programming.devel
summary    : Libguestfs is tools and a library for accessing and modifying guest disk images.
description: |
    ibguestfs is a set of tools for accessing and modifying virtual machine (VM) disk images.
builddeps  :
    - pkgconfig(hivex)
    - pkgconfig(augeas)
    - pkgconfig(libvirt)
    - pkgconfig(jansson)
    - pkgconfig(libconfig)
    - pkgconfig(ncursesw)
    - supermin
    - cdrtools-devel
    - ocaml-findlib
    - ocamlbuild
    - qemu
    - git
    - gperf
setup      : |
  export NCURSES_CONFIG=/usr/bin/ncursesw5-config
  %configure
build      : |
    %make
install    : |
    %make_install
