name       : magicmouse-trackpad-2 
version    : 0.0.0
release    : 1
source     :
    - https://github.com/rohitpid/Linux-Magic-Trackpad-2-Driver/archive/magicmouse2.zip : 026f590c4149a993be270f898f66aeaea6225d829d591d9cfc92113c9cf52491
license    : GPL-2.0-or-later # CHECK ME
summary    : Magicmouse 2 driver
description: |
    Apple magic mouse driver
builddeps  :
  - linux-current-headers
  - linux-current
setup      : |
    buildPath=linux/drivers/hid
    mv $buildPath/hid-magicmouse.c $buildPath/hid-magicmouse2.c
    sed -i 's/magicmouse\.o/magicmouse2\.o/g' $buildPath/Makefile
    sed -r -i 's/(^\t\.name \=)(.*)/\1 \"magicmouse2\"\,/g' $buildPath/hid-magicmouse2.c
build      : |
    cd linux/drivers/hid && make -C /lib/modules/$(uname -r)/build M=$PWD
install    : |
    path=$installdir/lib/modules/$(uname -r)/kernel/drivers/hid/
    install -D -d -m 00755 $path
    install -D -d -m 00755 $installdir/etc/X11/xorg.conf.d
    install -m 00644 usr/share/X11/xorg.conf.d/90-magictrackpad.conf $installdir/etc/X11/xorg.conf.d/90-magictrackpad.conf
    install -m 00644 linux/drivers/hid/hid-magicmouse2.ko $path/hid-magicmouse2.ko
 
