name       : irrtoolset
version    : 5.1.3
release    : 1
source     :
    - https://github.com/irrtoolset/irrtoolset/archive/release-5.1.3.tar.gz : a3eff14c2574f21be5b83302549d1582e509222d05f7dd8e5b68032ff6f5874a
license    : GPL-2.0-or-later, USC, RIPE NCC # CHECK ME
component  : networking.util
summary    : The IRRToolSet is a set of tools to work with Internet routing policies.
description: |
    The goal of the IRRToolSet is to make routing information more convenient and useful for network engineers, by providing tools for automated router configuration, routing policy analysis, and on-going maintenance.
builddeps  : []
setup      : |
    autoreconf -i
    %configure
build      : |
    %make
install    : |
    %make_install
