name       : hivex
version    : 1.3.18
release    : 1
source     :
    - http://download.libguestfs.org/hivex/hivex-1.3.18.tar.gz : 8a1e788fd9ea9b6e8a99705ebd0ff8a65b1bdee28e319c89c4a965430d0a7445
license    : LGPL v2.1
component  : programming.devel
summary    : library for reading and writing Windows Registry "hive" binary files.
description: |
    This is a self-contained library for reading and writing Windows Registry "hive" binary files. Unlike many other tools in this area, it doesn't use the textual .REG format for output, because parsing that is as much trouble as parsing the original binary format.  Instead it makes the file available through a C API, or there is a separate program to export the hive as XML.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(ruby-2.7)
    - ocamlbuild
    - ocaml-findlib
    - perl-module-build
    - perl-stringy
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    mkdir -p $installdir/usr/lib64/ocaml/site-lib
    cp -r $installdir/usr/lib64/ocaml/hivex $installdir/usr/lib64/ocaml/site-lib/
